policy:
  - name: t1
    description: GLOBAL
    scope: REGIONAL
    ip_address_version: IPV4
    addresses: ["1.1.1.1/32"]
    tags:
      Service: "Security"

  - name: t2
    description: LOCAL - TEST1
    scope: REGIONAL
    ip_address_version: IPV4
    addresses: ["2.2.2.2/32", "3.3.3.3/32"]
    tags:
      Service: "Security"

  - name: t3
    description: LOCAL - TEST3
    scope: REGIONAL
    ip_address_version: IPV4
    addresses: ["4.4.4.4/32"]
    tags:
      Service: "Security"